### PR TITLE
Update GNOME runtime to 3.28

### PR DESCRIPTION
**Pull request by alatiera**
I've only built and tested Firefox Dev Edition, It seems to work fine so far.

### CODE REVIEW

**Comment by wvengen** [comment]
Thanks, changes look fine! If someone wants to test the nightly, I think it could be merged.

Moving to flathub for the Gnome SDK would be preferable, in my view, since stable releases are used (and not the nightly SDK, as e.g. [Builder does](https://gitlab.gnome.org/GNOME/gnome-apps-nightly/raw/master/gnome-builder.flatpakref)).

**Comment by alatiera** [comment]
> Moving to flathub for the Gnome SDK would be preferable, in my view, since stable releases are used

Already done as part of #88 

> Thanks, changes look fine! If someone wants to test the nightly, I think it could be merged.

I will try to spin a new nightly build to test.

**Comment by alatiera** [comment]
just built Nightly 64.0a1 (2018-09-22). Its working fine.

**Comment by tpopela** [comment]
We will be updating the GNOME runtime to 3.32 or 3.34 (to be decided), once we fix the current crash that makes this Flatpak unusable.

**Comment by alatiera** [comment]
GNOME 3.32 is gonna likely be EOL by the end of the year, I'd suggest going with 3.34.

**Comment by erAck** [comment]
DevEdition and Nightly are at 3.34 now, UpstreamBinary binary uses org.freedesktop.Platform//19.08 runtime.

**Pull request closed without merging**
