### PR TITLE
Use the Rust Sdk Extension

### PR DESCRIPTION
**Pull request by alatiera**
Rust is popular enough that there's an Sdk extension that can be
used instead fo bundling and/or building Rust as a module.

The extension is distributed from flathub. It has branches for both
Freedesktop 1.6 and Freedesktop 18.08 based Sdks. The branch you
will need depends on the Sdk you are going to use. GNOME-sdk 3.26/28
are based upon freedesktop-sdk 1.6 while GNOME-sdk 3.30 will be based
upon Freedesktop-sdk 18.08.

The Sdk extensions are very well maintained, and updated usually upon release day.
I am the current maintainer of the 18.08 branch which can be found [here][1]
The 1.6 branch can be found [here][2]

[1]: https://gitlab.com/freedesktop-sdk/freedesktop-sdk/tree/18.08/elements/rust
[2]: https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable

### CODE REVIEW

**Comment by alatiera** [comment]
In 9a5b376ab24b1c146b2005434e3a058a14a49be0 I've changed the sdk repository to `flathub` instead.

The GNOME stable runtimes, ie 3.26, 3.28 etc, are distributed through flathub and the sdk.gnome.org repository has been deprecated and no longer receiving updates. Only the nightly/master runtime is is considered supported/updated in sdk.gnome.org.

**Comment by xhorak** [comment]
Hi, thanks for the patch. I wonder how often is the runtime updated. Usually when the new version of Firefox is released the required version of rust is bumped to latest stable in Nightly. Can we expect update of the rust sdk to be in time? Btw I like the idea, it's rather clumsy to update the version manually.

**Comment by alatiera** [comment]
> Hi, thanks for the patch. I wonder how often is the runtime updated. Usually when the new version of Firefox is released the required version of rust is bumped to latest stable in Nightly. Can we expect update of the rust sdk to be in time?

Yes totally, for a year now the Extension is updated the same day a new `rustc` version is released. Feel free to poke me if there is anything wrong with it in the future.

> Btw I like the idea, it's rather clumsy to update the version manually.

You also avoid building rustc which is a pain in itself

**Comment by xhorak** [comment]
@alatiera  We've got not completely unrelated issue for this one, but you might know: there seems to be a new dependency on the cbindgen (https://github.com/eqrion/cbindgen) which is a rust crate module with some dependencies on other crates. Any idea how can we handle this since we can't download during the build anything?

**Comment by alatiera** [comment]
There's a utility called `cargo-vendor` which pulls all the deps and then configures `cargo` to source the packages from the local archive. Firefox is probably already using it, though I am not sure how we can make it a flatpak module easily. The easiest thing is probably to vendor the sources before starting the flatpak build.

https://github.com/alexcrichton/cargo-vendor

**Pull request merged**
