### PR TITLE
update dev/nightly build to use yml

### PR DESCRIPTION
**Pull request by ritzk**
update builds to use yml over json
    
      - dev/nightly build
         - move from json to yaml
         - update cbindgen to 0.12
         - dconf is now provided by xdg-desktop-portal
         - firefox supports python3 for build
         - use flathub/shared-modules for common build deps
           - [ cpython2, gtk2, dbus-glib]
         - share common deps across projects
             - update nodejs to 12.xx lts
               - nodejs-gpy requires python2 to build
         - remove libraries provided by org.gnome.Sdk//3.34
            - [nasm, libnotify, pipewire]
      - install.sh: install to user profile
      - setup_runtime.sh: update rust-stable to point to 19.08

### CODE REVIEW

**Comment by lionirdeadman** [comment]
Should probably use shared modules like it was done with org.mozilla.FirefoxDevEdition

**Comment by ritzk** [comment]
Needs https://gitlab.com/freedesktop-sdk/freedesktop-sdk/merge_requests/1905 , to build firefox nightly locally

**Comment by lionirdeadman** [comment]
Ah, so I wasn't crazy. Good to know.

**Comment by ritzk** [comment]
I ended up using https://github.com/flathub/org.freedesktop.Sdk.Extension.rust-stable . Modified the branch to state 19.08, until upstream is fixed.

**Comment by mrmcq2u** [comment]
Still waiting on upstream before merging this?

**Comment by erAck** [comment]
While yaml may be easier to read (it even _might_ be easier to write..) than json, the flatpak-build native manifest format is json and yaml is automatically converted to json, for which if there are errors the diagnostics can get "pretty cryptic". Sticking with json here probably is preferable.

**Pull request closed without merging**
